CREATE TABLE FILM(
FilmID int NOT NULL,
FilmName varchar(30) NOT NULL,
Genre varchar(30) NOT NULL,
IMDbRating real  NULL,
Description varchar(1000) NULL,
Release_date int NULL,
Country varchar(40) NULL,
CONSTRAINT FilmPK
PRIMARY KEY (FilmID));

CREATE TABLE ACTOR(
ActorID int NOT NULL,
ActorFIO varchar(30) NOT NULL,
CONSTRAINT ActorPK
PRIMARY KEY (ActorID));

CREATE TABLE ACTOR_FILM(
ActorID int NOT NULL,
FilmID int NOT NULL,
CONSTRAINT ActorFilmPK
PRIMARY KEY (ActorID, FilmID),
CONSTRAINT Actor_Film_ActorFK
FOREIGN KEY (ActorID)
REFERENCES ACTOR (ActorID)
ON DELETE CASCADE,
CONSTRAINT Actor_Film_FilmFK
FOREIGN KEY (FilmID)
REFERENCES FILM (FilmID)
ON DELETE CASCADE);

CREATE TABLE PRODUCER(
ProducerID int NOT NULL,
ProducerFIO varchar(30) NOT NULL,
CONSTRAINT ProducerPK
PRIMARY KEY (ProducerID));

CREATE TABLE FILM_PRODUCER(
FilmID int NOT NULL,
ProducerID int NOT NULL,
CONSTRAINT FilmProducerPK
PRIMARY KEY (FilmID, ProducerID),
CONSTRAINT Film_Producer_ProducerFK
FOREIGN KEY (ProducerID)
REFERENCES PRODUCER (ProducerID)
ON DELETE CASCADE,
CONSTRAINT Film_Producer_FilmFK
FOREIGN KEY (FilmID)
REFERENCES FILM (FilmID)
ON DELETE CASCADE);

CREATE TABLE MOVIE_REVIEW(
ReviewID int NOT NULL,
NickName varchar(30) NOT NULL,
ReviewText varchar(1000) NULL,
FilmID int NOT NULL,
CONSTRAINT ReviewPK
PRIMARY KEY (ReviewID),
CONSTRAINT FilmFK
FOREIGN KEY (FilmID)
REFERENCES FILM (FilmID));

CREATE SEQUENCE SEQ_FILM
INCREMENT BY 1
START WITH 101
MINVALUE 100;

CREATE SEQUENCE SEQ_ACTOR
INCREMENT BY 1
START WITH 201
MINVALUE 200;

CREATE SEQUENCE SEQ_PRODUCER
INCREMENT BY 1
START WITH 301
MINVALUE 300;

CREATE SEQUENCE SEQ_MOVIEREVIEW
INCREMENT BY 1
START WITH 401
MINVALUE 400;
